language: node_js
node_js:
  - lts/*
install:
  - npm install
  - lerna bootstrap
dist: trusty
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=08a773cb4ea5811add5a45e12873e5cd2634c005568705cc37abfd5217617a32
before_script:
  - git config core.autocrlf false
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - lerna run test --stream
after_script:
  # See https://github.com/codeclimate/test-reporter/issues/263
  - |
      if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then
        for f in packages/*; do
          if [ -d $f]; then
            echo $f;
            ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
          fi
        done;
        ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
        ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
      fi
deploy:
  provider: script
  skip_cleanup: true
  script:
    - echo -e "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN\nemail=$NPM_AUTH_EMAIL" > ~/.npmrc
    - cat ~/.npmrc
    - NPM_USER=`npm whoami`
    - echo -e "Publishing to npm as $NPM_USER...\n"
    - lerna publish --yes --loglevel=silly
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = "cron"
