
language: node_js
node_js:
  - "lts/*"
install:
  - npm install 
  - lerna bootstrap
dist: trusty
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=08a773cb4ea5811add5a45e12873e5cd2634c005568705cc37abfd5217617a32
before_script:
  # Commented out for local testing only on MacOS
  #- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - lerna run test
after_script:
  - ./cc-test-reporter format-coverage -t lcov after-build .exit $TRAVIS_TEST_RESULT